version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            virtualenv venv
            . venv/bin/activate
      - run:
          name: Install numpy
          command: |
            . venv/bin/activate
            pip install numpy
      - run:
          name: Install SigProPy
          command: |
            . venv/bin/activate
            pip install git+ssh://git@github.com/jpvantassel/signal-processing.git
      - run:
          name: Install hvsrpy and dependencies
          command: |
            . venv/bin/activate
            pip install -e .[dev]
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd test
            python -m unittest

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.5
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0
