version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@14.0.0
  codecov: codecov/codecov@4.1.0

workflows:
  build:
    jobs:
      - test-38:
          context:
            - docker
      - test-39:
          context:
            - docker
      - test-310:
          context:
            - docker
      - test-311:
          context:
            - docker
      - test-312:
          context:
            - docker

jobs:
  test-38: &test-template
    docker:
      - image: cimg/python:3.8.19
        auth:
          username: jpvantassel
          password: $DOCKER_PASS
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create and Activate Virtual Environment
          command: |
            virtualenv venv
            source venv/bin/activate
      - run:
          name: Install hvsrpy and Dependencies
          command: |
            source venv/bin/activate
            python -m pip install -e .[dev]
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            cd test
            coverage run --source=../hvsrpy -m unittest
            coverage xml -o coverage.xml
      - codecov/upload
      - coverage-reporter/send_report

  test-39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9.19
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10.14
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11.9
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-312:
    <<: *test-template
    docker:
      - image: cimg/python:3.12.4
        auth:
          username: jpvantassel
          password: $DOCKER_PASS
